project:
  type: website
  render:
    - index.qmd
    - discrete-choice.qmd
  # render for gh-pages
  output-dir: docs

website:
  title: "Odum Discrete Choice Models"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true